package app.openpdf.foss.ui.theme

import androidx.compose.ui.graphics.Color

// Calm Material palette — every value derives from the brand seed #2C3E50
// (see design/calm-material-design-system). Components must reference the
// MaterialTheme color scheme, never these constants directly.

// Light
val PrimaryLight = Color(0xFF2C3E50)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD2E4F9)
val OnPrimaryContainerLight = Color(0xFF0A1D2C)
val SecondaryLight = Color(0xFF52606F)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD5E4F7)
val OnSecondaryContainerLight = Color(0xFF0E1D2A)
val TertiaryLight = Color(0xFF69587A)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFF0DBFF)
val OnTertiaryContainerLight = Color(0xFF241533)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val SurfaceLight = Color(0xFFFCFCFD)
val OnSurfaceLight = Color(0xFF1A1C1E)
val SurfaceVariantLight = Color(0xFFDFE2EB)
val OnSurfaceVariantLight = Color(0xFF42474E)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF6F7F9)
val SurfaceContainerLight = Color(0xFFF0F1F4)
val SurfaceContainerHighLight = Color(0xFFEBEDF0)
val SurfaceContainerHighestLight = Color(0xFFE7E9EC)
val OutlineLight = Color(0xFF72777F)
val OutlineVariantLight = Color(0xFFC5C9CE)
val InverseSurfaceLight = Color(0xFF2F3033)
val InverseOnSurfaceLight = Color(0xFFF1F0F4)
val InversePrimaryLight = Color(0xFF9BCBFA)

// Dark
val PrimaryDark = Color(0xFF7FA8C9)
val OnPrimaryDark = Color(0xFF0B2237)
val PrimaryContainerDark = Color(0xFF243546)
val OnPrimaryContainerDark = Color(0xFFD2E4F9)
val SecondaryDark = Color(0xFFB9C8DA)
val OnSecondaryDark = Color(0xFF233240)
val SecondaryContainerDark = Color(0xFF3A4857)
val OnSecondaryContainerDark = Color(0xFFD5E4F7)
val TertiaryDark = Color(0xFFD4BFE6)
val OnTertiaryDark = Color(0xFF392A49)
val TertiaryContainerDark = Color(0xFF504061)
val OnTertiaryContainerDark = Color(0xFFF0DBFF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val SurfaceDark = Color(0xFF121417)
val OnSurfaceDark = Color(0xFFE2E2E6)
val SurfaceVariantDark = Color(0xFF42474E)
val OnSurfaceVariantDark = Color(0xFFC2C7CF)
val SurfaceContainerLowestDark = Color(0xFF0D0F12)
val SurfaceContainerLowDark = Color(0xFF1A1C1F)
val SurfaceContainerDark = Color(0xFF1E2023)
val SurfaceContainerHighDark = Color(0xFF242629)
val SurfaceContainerHighestDark = Color(0xFF2A2D31)
val OutlineDark = Color(0xFF8C9199)
val OutlineVariantDark = Color(0xFF42474E)
val InverseSurfaceDark = Color(0xFFE2E2E6)
val InverseOnSurfaceDark = Color(0xFF2F3033)
val InversePrimaryDark = Color(0xFF2C3E50)
